services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: merp_app_dev
    container_name: merp_app_dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "9000:9000"
    networks:
      - merp_net_dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: merp_db_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: merp
      MYSQL_USER: merp
      MYSQL_PASSWORD: merp
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - merp_net_dev

  nginx:
    image: nginx:alpine
    container_name: merp_nginx_dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www
    ports:
      - "8085:80"
    depends_on:
      - app
    networks:
      - merp_net_dev


networks:
  merp_net_dev:
    driver: bridge

volumes:
  mysql-data:
